import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";

import PageHero from "@/components/shared/page-hero";
import { DetailPageSkeleton } from "@/components/shared/page-skeletons";
import { Button } from "@/components/ui/button";
import {
  getAiTourHistory,
  getAiTourHistoryDetail,
  updateTravelerAiProposalDecision,
} from "@/services/api/ai";
import EmptyHistoryState from "./EmptyHistoryState";
import TourHistoryDetail from "./TourHistoryDetail";
import TourHistoryList from "./TourHistoryList";

export default function AITourHistory() {
  const navigate = useNavigate();
  const [history, setHistory] = useState([]);
  const [selectedTour, setSelectedTour] = useState(null);
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);
  const [decisionLoading, setDecisionLoading] = useState(false);

  const formatDate = (value) => {
    if (!value) return "No start date";

    return new Date(value).toLocaleDateString("en", {
      month: "short",
      day: "2-digit",
      year: "numeric",
    });
  };

  const getTotal = (data = {}) =>
    (Number(data.ADULT) || 0) +
    (Number(data.CHILD) || 0) +
    (Number(data.INFANT) || 0);

  const getTotalActivities = (tour) =>
    tour?.itineraries?.reduce(
      (total, day) => total + (day.activities?.length || 0),
      0,
    ) || 0;

  const loadHistory = async () => {
    try {
      setLoading(true);
      const response = await getAiTourHistory();
      const items = response.data.data || [];
      setHistory(items);
      setSelectedTour(items[0] || null);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Cannot load AI history");
    } finally {
      setLoading(false);
    }
  };

  const handleSelectTour = async (tour) => {
    try {
      setSelectedTour(tour);
      setDetailLoading(true);
      const response = await getAiTourHistoryDetail(tour._id);
      setSelectedTour(response.data.data);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Cannot load tour detail");
    } finally {
      setDetailLoading(false);
    }
  };

  const handleBackToPlanner = () => {
    navigate("/traveler/ai-travel-planner", {
      state: selectedTour ? { selectedTour } : null,
    });
  };

  const handleDecision = async (decision) => {
    if (!selectedTour?._id) return;

    try {
      setDecisionLoading(true);
      const response = await updateTravelerAiProposalDecision(selectedTour._id, decision);
      const updated = response.data.data;

      setSelectedTour(updated);
      setHistory((prev) =>
        prev.map((item) =>
          item._id === updated._id
            ? {
                ...item,
                status: updated.status,
                convertedTourId: updated.convertedTourId,
              }
            : item,
        ),
      );

      toast.success(
        decision === "approve"
          ? "Bạn đã đồng ý tour đề xuất từ provider"
          : "Bạn đã từ chối tour đề xuất này",
      );
    } catch (error) {
      toast.error(error?.response?.data?.message || "Không thể cập nhật quyết định");
    } finally {
      setDecisionLoading(false);
    }
  };

  useEffect(() => {
    loadHistory();
  }, []);

  return (
    <main className="relative flex min-w-0 flex-1 flex-col overflow-hidden bg-surface">
      <div className="mx-auto w-full px-6 pb-12 pt-24 md:px-10">
      <PageHero
        className="mb-8"
        eyebrow="Traveler Archive"
        heading={
          <>
            AI Tour{" "}
            <span className="rounded-xl bg-primary/8 px-2 py-1 italic text-primary">
              History
            </span>
          </>
        }
        description="Saved plans generated by your AI travel planner account."
        actions={
          <>
            <Button
              type="button"
              variant="outline"
              onClick={handleBackToPlanner}
              className="rounded-xl bg-white px-5 font-semibold"
            >
              Back to Planner
            </Button>
            <Button
              type="button"
              onClick={loadHistory}
              className="rounded-xl bg-teal-600 px-5 font-semibold hover:bg-teal-700"
            >
              Refresh
            </Button>
          </>
        }
      />

      {loading ? (
        <DetailPageSkeleton />
      ) : history.length === 0 ? (
        <EmptyHistoryState />
      ) : (
        <div className="grid gap-6 lg:grid-cols-[420px_1fr]">
          <TourHistoryList
            history={history}
            selectedTourId={selectedTour?._id}
            onSelectTour={handleSelectTour}
            formatDate={formatDate}
            getTotal={getTotal}
          />
          <TourHistoryDetail
            detailLoading={detailLoading}
            selectedTour={selectedTour}
            formatDate={formatDate}
            getTotal={getTotal}
            totalActivities={getTotalActivities(selectedTour)}
            decisionLoading={decisionLoading}
            onDecision={handleDecision}
            onViewProposal={(tourId) => navigate(`/traveler/tour-detail/${tourId}`)}
          />
        </div>
      )}
      </div>
    </main>
  );
}
