import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getAiTourHistory, getAiTourHistoryDetail } from "@/services/api/ai";
import EmptyHistoryState from "./EmptyHistoryState";
import TourHistoryDetail from "./TourHistoryDetail";
import TourHistoryList from "./TourHistoryList";

export default function AITourHistory() {
  const navigate = useNavigate();
  const [history, setHistory] = useState([]);
  const [selectedTour, setSelectedTour] = useState(null);
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);

  const formatDate = (value) => {
    if (!value) return "No start date";

    return new Date(value).toLocaleDateString("en", {
      month: "short",
      day: "2-digit",
      year: "numeric",
    });
  };

  const getTotal = (data = {}) =>
    (Number(data.ADULT) || 0) +
    (Number(data.CHILD) || 0) +
    (Number(data.INFANT) || 0);

  const getTotalActivities = (tour) =>
    tour?.itineraries?.reduce(
      (total, day) => total + (day.activities?.length || 0),
      0,
    ) || 0;

  const loadHistory = async () => {
    try {
      setLoading(true);
      const response = await getAiTourHistory();
      const items = response.data.data || [];
      setHistory(items);
      setSelectedTour(items[0] || null);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Cannot load AI history");
    } finally {
      setLoading(false);
    }
  };

  const handleSelectTour = async (tour) => {
    try {
      setSelectedTour(tour);
      setDetailLoading(true);
      const response = await getAiTourHistoryDetail(tour._id);
      setSelectedTour(response.data.data);
    } catch (error) {
      toast.error(error?.response?.data?.message || "Cannot load tour detail");
    } finally {
      setDetailLoading(false);
    }
  };

  const handleBackToPlanner = () => {
    navigate("/traveler/ai-travel-planner", {
      state: selectedTour ? { selectedTour } : null,
    });
  };

  useEffect(() => {
    loadHistory();
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 px-6 py-8">
      <header className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <h1 className="brand-font mb-2 text-4xl font-extrabold tracking-tight text-on-surface">
            AI Tour History
          </h1>
          <p className="font-body max-w-2xl text-lg text-on-surface-variant">
            Saved plans generated by your AI travel planner account.
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <Button
            type="button"
            variant="outline"
            onClick={handleBackToPlanner}
            className="rounded-xl bg-white px-5 font-semibold"
          >
            Back to Planner
          </Button>
          <Button
            type="button"
            onClick={loadHistory}
            className="rounded-xl bg-teal-600 px-5 font-semibold hover:bg-teal-700"
          >
            Refresh
          </Button>
        </div>
      </header>

      {loading ? (
        <div className="flex min-h-[420px] items-center justify-center rounded-3xl border border-slate-200 bg-white text-sm font-semibold text-slate-500">
          Loading AI tour history...
        </div>
      ) : history.length === 0 ? (
        <EmptyHistoryState />
      ) : (
        <div className="grid gap-6 lg:grid-cols-[420px_1fr]">
          <TourHistoryList
            history={history}
            selectedTourId={selectedTour?._id}
            onSelectTour={handleSelectTour}
            formatDate={formatDate}
            getTotal={getTotal}
          />
          <TourHistoryDetail
            detailLoading={detailLoading}
            selectedTour={selectedTour}
            formatDate={formatDate}
            getTotal={getTotal}
            totalActivities={getTotalActivities(selectedTour)}
          />
        </div>
      )}
    </div>
  );
}
