POST http://localhost:3000/api/tours
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGI0NjhhNjU2Mjc3YzFlZDk1NzUyOSIsImlhdCI6MTc3NjE2MjU2OCwiZXhwIjoxNzc2MTYzNDY4fQ.DPCT3i78yTPqCVyQ8tAJNop-RK4ShzaayQWpwGslsH0

{
  "quantity": 20,
  "price": 1500000,
  "location": "Da Nang",
  "description": "Tour tham quan Đà Nẵng 3 ngày 2 đêm",
  "numberOfDay": 3,
  "startDay": "2026-05-01T00:00:00.000Z",
  "type": "GROUP",
  "minSlots": 5,
  "maxSlots": 20,
  "isActive": true,
  "itineraries": [
    {
      "dayNumber": 1,
      "description": "Tham quan các địa điểm nổi bật trong thành phố",
      "activities": [
        {
          "time": "08:00",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2ef"
        },
        {
          "time": "10:00",
          "title": "Tham quan Cầu Rồng",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2f2"
        }
      ]
    },
    {
      "dayNumber": 2,
      "description": "Trải nghiệm cáp treo và Golden Bridge",
      "activities": [
        {
          "time": "08:30",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2f4"
        },
        {
          "time": "11:00",
          "title": "Check-in Cầu Vàng",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2f6"
        }
      ]
    },
    {
      "dayNumber": 3,
      "description": "Thư giãn và trả khách",
      "activities": [
        {
          "time": "09:00",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2f8"
        },
        {
          "time": "12:00",
          "title": "Kết thúc tour",
          "statusActivity": "NOT_DONE",
          "serviceId": "69de1a470a4f2be4380fa2fb"
        }
      ]
    }
  ]
}

###
GET http://localhost:3000/api/tours
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGI0NjhhNjU2Mjc3YzFlZDk1NzUyOSIsImlhdCI6MTc3NjE2MjU2OCwiZXhwIjoxNzc2MTYzNDY4fQ.DPCT3i78yTPqCVyQ8tAJNop-RK4ShzaayQWpwGslsH0


###
GET http://localhost:3000/api/tours/69de1a884f6678778d99639a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGI0NjhhNjU2Mjc3YzFlZDk1NzUyOSIsImlhdCI6MTc3NjE2NDc5MSwiZXhwIjoxNzc2MTY1NjkxfQ.jlCV19XX45k1XGEIufuoixggTdON7rxyiNFkMu1UXcY


###
PUT http://localhost:3000/api/tours/69de1a884f6678778d99639a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGI0NjhhNjU2Mjc3YzFlZDk1NzUyOSIsImlhdCI6MTc3NjE2NDc5MSwiZXhwIjoxNzc2MTY1NjkxfQ.jlCV19XX45k1XGEIufuoixggTdON7rxyiNFkMu1UXcY

{
  "price": 2000000,
  "location": "Hoi An",
  "itineraries": [
    {
      "dayNumber": 1,
      "activities": [
        {
          "time": "09:00",
          "title": "Đi ăn sáng",
          "serviceId": "69de1a470a4f2be4380fa2ef"
        }
      ]
    }
  ]
}

###
DELETE http://localhost:3000/api/tours/69de1a884f6678778d99639a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGI0NjhhNjU2Mjc3YzFlZDk1NzUyOSIsImlhdCI6MTc3NjE2NDc5MSwiZXhwIjoxNzc2MTY1NjkxfQ.jlCV19XX45k1XGEIufuoixggTdON7rxyiNFkMu1UXcY

