export function buildAuthCopy(language) {
  if (language === "vi") {
    return {
      shell: {
        backHome: "Về trang chủ",
        accessLabel: "Khu vực riêng cho traveler",
        clubLabel: "Không gian traveler SmartTravel",
        secureFlow: "SmartTravel Vietnam - luồng xác thực bảo mật",
      },
      featurePanel: {
        protectedAccess: "Truy cập bảo mật",
        refinedBy: "Được AI lên kế hoạch và chuyên gia bản địa tinh chỉnh",
        verifiedTraveler: "Traveler đã xác minh",
      },
      loginPage: {
        badge: "Traveler quay lại",
        title: "Quay lại hành trình bạn đang dở dang.",
        description:
          "Đăng nhập để mở lại itinerary, lịch sử lên kế hoạch bằng AI, đặt chỗ và theo dõi chuyến đi trong một không gian gọn gàng hơn.",
        journeyLabel: "Hành trình đã lưu",
        journeyTitle: "Đà Nẵng - Hội An - Huế",
        journeyDates: "07/06 - 13/06",
        stats: [
          { value: "6", label: "đêm đã lưu" },
          { value: "11", label: "điểm dừng đẹp" },
          { value: "24/7", label: "truy cập lịch trình" },
        ],
        quote:
          "Mọi thứ từ planning đến theo dõi chuyến đi đều mượt và có cảm giác rất chỉn chu.",
        quoteAuthor: "Amelia R. - New Zealand",
        shellTitle: "Chào mừng quay lại",
        shellDescription: "",
        tabs: {
          login: "Đăng nhập",
          signup: "Đăng ký",
        },
      },
      loginForm: {
        googleIdle: "Đăng nhập với Google",
        googleLoading: "Đang kết nối Google...",
        divider: "hoặc tiếp tục bằng email",
        infoEyebrow: "Dành cho traveler quay lại",
        infoBody:
          "Mở lại lịch trình đã lưu, điểm chốt booking và toàn bộ lịch sử lên kế hoạch trong một nơi duy nhất.",
        emailLabel: "Địa chỉ email",
        emailPlaceholder: "ban@example.com",
        passwordLabel: "Mật khẩu",
        passwordPlaceholder: "Nhập mật khẩu",
        forgotPassword: "Quên mật khẩu?",
        rememberMe: "Giữ tôi luôn đăng nhập",
        travelerAccount: "Tài khoản traveler",
        submitIdle: "Đăng nhập",
        submitLoading: "Đang đăng nhập...",
        footerText: "Chưa có tài khoản?",
        footerLink: "Đăng ký ngay",
      },
      registerPage: {
        badge: "Đăng ký riêng tư",
        title: "Việt Nam được thiết kế lại theo đúng cách bạn muốn đi.",
        description:
          "Tạo tài khoản traveler để lưu hành trình, tinh chỉnh với AI, xác nhận booking và theo dõi mọi bước tiếp theo rõ ràng hơn.",
        journeyLabel: "Bản nháp đầu tiên",
        journeyTitle: "Vịnh Hạ Long - Lan Hạ - Ninh Bình",
        journeyDates: "Dựng trong chưa đầy 2 phút",
        stats: [
          { value: "AI", label: "trợ lý lên kế hoạch" },
          { value: "1", label: "tài khoản hợp nhất" },
          { value: "200+", label: "đối tác địa phương" },
        ],
        quote:
          "Ngay từ màn hình đăng ký đã có cảm giác như bước vào một studio du lịch cao cấp.",
        quoteAuthor: "Clara P. - Singapore",
        shellTitle: "Tạo tài khoản",
        shellDescription: "",
        tabs: {
          signup: "Đăng ký",
          login: "Đăng nhập",
        },
      },
      registerForm: {
        googleIdle: "Đăng ký với Google",
        googleLoading: "Đang kết nối Google...",
        divider: "hoặc tạo tài khoản bằng email",
        infoEyebrow: "Hồ sơ traveler",
        infoBody:
          "Tài khoản của bạn mở ra itinerary đã lưu, tinh chỉnh bằng AI, booking và tiến độ chuyến đi trong cùng một nơi.",
        fullNameLabel: "Họ và tên",
        fullNamePlaceholder: "Nguyen Minh Anh",
        emailLabel: "Địa chỉ email",
        emailPlaceholder: "ban@example.com",
        passwordLabel: "Mật khẩu",
        passwordPlaceholder: "Tạo mật khẩu",
        confirmPasswordLabel: "Xác nhận mật khẩu",
        confirmPasswordPlaceholder: "Nhập lại mật khẩu",
        passwordChecks: [
          "Tối thiểu 8 ký tự",
          "Có chữ hoa và chữ thường",
          "Có số hoặc ký hiệu",
        ],
        policy:
          "Tôi đồng ý với điều khoản sử dụng, chính sách riêng tư và thông báo liên quan đến hành trình.",
        submitIdle: "Tạo tài khoản",
        submitLoading: "Đang gửi OTP xác minh...",
        footerText: "Đã có tài khoản?",
        footerLink: "Đăng nhập",
        footerBadge: "Xác minh bằng OTP bảo mật",
      },
      forgotPage: {
        badge: "Khôi phục mật khẩu",
        title: "Lấy lại quyền truy cập mà không bị rối.",
        description:
          "Chúng tôi sẽ gửi OTP bảo mật đến email của bạn để xác nhận quyền sở hữu trước khi đặt mật khẩu mới.",
        journeyLabel: "Khôi phục an toàn",
        journeyTitle: "Kênh đặt lại riêng tư",
        journeyDates: "Mã xác minh 6 chữ số",
        stats: [
          { value: "6", label: "chữ số OTP" },
          { value: "10m", label: "thời gian hiệu lực" },
          { value: "1", label: "bước xác nhận inbox" },
        ],
        quote:
          "Luồng khôi phục cho cảm giác bình tĩnh và đáng tin hơn hẳn nhiều sản phẩm du lịch khác.",
        quoteAuthor: "David K. - Canada",
        shellTitle: "Quên mật khẩu",
        shellDescription:
          "Nhập email của bạn và chúng tôi sẽ gửi một mã OTP dùng một lần để đặt lại tài khoản.",
        footerText: "Nhớ mật khẩu rồi?",
        footerLink: "Quay lại đăng nhập",
        infoEyebrow: "Khôi phục an toàn",
        infoBody:
          "Chúng tôi gửi một mã 6 chữ số tới email traveler của bạn để chỉ bạn mới có thể tiếp tục đặt mật khẩu mới.",
        emailLabel: "Địa chỉ email",
        emailPlaceholder: "ban@example.com",
        submitIdle: "Gửi OTP đặt lại",
        submitLoading: "Đang gửi OTP...",
        footerBadge: "Checkpoint bảo mật cho traveler",
      },
      verifyEmailPage: {
        badge: "Bảo vệ email",
        title: "Chỉ còn một bước nhỏ trước khi bắt đầu.",
        description:
          "Xác minh email bằng mã OTP vừa được gửi để tài khoản traveler của bạn được bảo vệ ngay từ đầu.",
        journeyLabel: "Cổng kích hoạt",
        journeyTitle: "Xác minh tài khoản traveler",
        journeyDates: "Nhập mã email 6 chữ số",
        stats: [
          { value: "6", label: "chữ số cần nhập" },
          { value: "OTP", label: "thử thách email" },
          { value: "Ngay", label: "kích hoạt tức thì" },
        ],
        quote:
          "Mình thích việc luồng đăng ký vẫn giữ được cảm giác tinh tế đến cả bước xác minh.",
        quoteAuthor: "Mira S. - Đức",
        shellTitle: "Xác minh email",
        shellDescription:
          "Nhập mã OTP 6 chữ số từ hộp thư để kích hoạt tài khoản của bạn.",
        footerText: "Đã xác minh xong?",
        footerLink: "Đi tới đăng nhập",
        infoEyebrow: "Bảo vệ email",
        infoBody:
          "Dùng mã vừa gửi để xác nhận bạn sở hữu email này trước khi itinerary đầu tiên được kích hoạt.",
        emailLabel: "Địa chỉ email",
        emailPlaceholder: "ban@example.com",
        otpLabel: "Mã OTP xác minh",
        submitIdle: "Xác minh tài khoản",
        submitLoading: "Đang xác minh...",
        resendIdle: "Gửi lại OTP",
        resendLoading: "Đang gửi lại OTP...",
      },
      verifyResetPage: {
        badge: "Xác thực OTP",
        title: "Kiểm tra hộp thư để lấy mã đặt lại.",
        description:
          "Nhập mã OTP một lần được gửi qua email, sau đó chúng tôi sẽ đưa bạn tới màn hình đặt mật khẩu mới.",
        journeyLabel: "Điểm xác nhận",
        journeyTitle: "Kiểm tra mã đặt lại",
        journeyDates: "Cần OTP từ email",
        stats: [
          { value: "6", label: "chữ số cần nhập" },
          { value: "1", label: "bước tới mật khẩu mới" },
          { value: "Nhanh", label: "luồng khôi phục" },
        ],
        quote:
          "Từng bước trong luồng khôi phục đều rõ ràng nên mình không bao giờ bị mất phương hướng.",
        quoteAuthor: "Sophie T. - Pháp",
        shellTitle: "Xác minh OTP đặt lại",
        shellDescription: "Dùng mã OTP 6 chữ số từ email để tiếp tục.",
        footerText: "Muốn dùng email khác?",
        footerLink: "Bắt đầu lại",
        infoEyebrow: "Khôi phục được bảo vệ",
        infoBody:
          "Xác nhận mã đặt lại từ hộp thư và chúng tôi sẽ đưa bạn thẳng tới màn hình tạo mật khẩu mới.",
        emailLabel: "Địa chỉ email",
        emailPlaceholder: "ban@example.com",
        otpLabel: "OTP đặt lại",
        submitIdle: "Tiếp tục",
        submitLoading: "Đang kiểm tra OTP...",
        resendIdle: "Gửi lại OTP",
        resendLoading: "Đang gửi lại OTP...",
      },
      resetPage: {
        badge: "Làm mới thông tin đăng nhập",
        title: "Tạo mật khẩu sẵn sàng cho chuyến đi tiếp theo.",
        description:
          "OTP đặt lại đã được xác minh. Hãy đặt mật khẩu mới và quay lại dashboard traveler của bạn.",
        journeyLabel: "Đặt lại đã duyệt",
        journeyTitle: "Làm mới thông tin truy cập",
        journeyDates: "Cần mật khẩu mới",
        stats: [
          { value: "2", label: "trường còn lại" },
          { value: "OTP", label: "đã xác nhận" },
          { value: "An toàn", label: "quay lại bảo mật" },
        ],
        quote:
          "Ngay cả phần đặt lại mật khẩu cũng có cảm giác được chăm chút chứ không phải chắp vá.",
        quoteAuthor: "Noah F. - Hoa Kỳ",
        shellTitle: "Đặt mật khẩu mới",
        shellDescription: "Chọn mật khẩu mới cho tài khoản của bạn.",
        footerText: "Cần một OTP khác?",
        footerLink: "Yêu cầu lại",
        infoEyebrow: "Làm mới mật khẩu",
        infoBody:
          "Chọn một mật khẩu mạnh cho tài khoản traveler gắn với email đã được xác minh này.",
        emailLabel: "Địa chỉ email",
        passwordLabel: "Mật khẩu mới",
        passwordPlaceholder: "Tạo mật khẩu mới",
        confirmPasswordLabel: "Xác nhận mật khẩu",
        confirmPasswordPlaceholder: "Nhập lại mật khẩu mới",
        passwordChecks: [
          "Tối thiểu 8 ký tự",
          "Có chữ hoa và chữ thường",
          "Có số hoặc ký hiệu",
        ],
        submitIdle: "Đặt lại mật khẩu",
        submitLoading: "Đang cập nhật mật khẩu...",
      },
    };
  }

  return {
    shell: {
      backHome: "Back home",
      accessLabel: "Private traveler access",
      clubLabel: "SmartTravel traveler club",
      secureFlow: "SmartTravel Vietnam - secure sign-in flow",
    },
    featurePanel: {
      protectedAccess: "Protected access",
      refinedBy: "Refined by AI planning and local specialists",
      verifiedTraveler: "Verified traveler",
    },
    loginPage: {
      badge: "Returning traveler",
      title: "Return to the journey you were shaping.",
      description:
        "Log in to reopen your itinerary, AI planning history, bookings, and live trip tracking in a calmer traveler space.",
      journeyLabel: "Saved itinerary",
      journeyTitle: "Da Nang - Hoi An - Hue",
      journeyDates: "June 07 - June 13",
      stats: [
        { value: "6", label: "nights retained" },
        { value: "11", label: "stops saved" },
        { value: "24/7", label: "trip access" },
      ],
      quote:
        "Everything from planning to trip tracking felt smooth and unusually well put together.",
      quoteAuthor: "Amelia R. - New Zealand",
      shellTitle: "Welcome back",
      shellDescription: "",
      tabs: {
        login: "Log in",
        signup: "Sign up",
      },
    },
    loginForm: {
      googleIdle: "Log in with Google",
      googleLoading: "Connecting Google...",
      divider: "or continue with email",
      infoEyebrow: "For returning travelers",
      infoBody:
        "Reopen saved itineraries, booking checkpoints, and your planning history in one clean space.",
      emailLabel: "Email address",
      emailPlaceholder: "alex@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      forgotPassword: "Forgot password?",
      rememberMe: "Keep me signed in",
      travelerAccount: "Traveler account",
      submitIdle: "Log in",
      submitLoading: "Logging you in...",
      footerText: "New to SmartTravel?",
      footerLink: "Sign up now",
    },
    registerPage: {
      badge: "Private sign-up",
      title: "Vietnam, reimagined for the way you want to travel.",
      description:
        "Create your traveler account to save itineraries, refine plans with AI, confirm bookings, and track every next step with more clarity.",
      journeyLabel: "First draft preview",
      journeyTitle: "Ha Long Bay - Lan Ha - Ninh Binh",
      journeyDates: "Built in under 2 minutes",
      stats: [
        { value: "AI", label: "planning assistant" },
        { value: "1", label: "unified account" },
        { value: "200+", label: "local partners" },
      ],
      quote:
        "Even the sign-up flow felt like entering a premium travel studio instead of a generic form.",
      quoteAuthor: "Clara P. - Singapore",
      shellTitle: "Create your account",
      shellDescription: "",
      tabs: {
        signup: "Sign up",
        login: "Log in",
      },
    },
    registerForm: {
      googleIdle: "Sign up with Google",
      googleLoading: "Connecting Google...",
      divider: "or create your account with email",
      infoEyebrow: "Traveler profile",
      infoBody:
        "Your account unlocks saved itineraries, AI refinement, bookings, and live trip progress in one place.",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Alex Nguyen",
      emailLabel: "Email address",
      emailPlaceholder: "alex@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Create a password",
      confirmPasswordLabel: "Confirm password",
      confirmPasswordPlaceholder: "Re-enter your password",
      passwordChecks: [
        "At least 8 characters",
        "Uppercase and lowercase letters",
        "One number or symbol",
      ],
      policy:
        "I agree to the terms of service, privacy policy, and traveler communication updates.",
      submitIdle: "Create account",
      submitLoading: "Sending verification OTP...",
      footerText: "Already have an account?",
      footerLink: "Log in",
      footerBadge: "Verification by secure OTP",
    },
    forgotPage: {
      badge: "Password recovery",
      title: "Regain access without the stress.",
      description:
        "We will send a secure OTP to your email so you can confirm ownership before setting a new password.",
      journeyLabel: "Secure recovery",
      journeyTitle: "Private reset channel",
      journeyDates: "Six-digit verification code",
      stats: [
        { value: "6", label: "OTP digits" },
        { value: "10m", label: "typical validity" },
        { value: "1", label: "inbox checkpoint" },
      ],
      quote:
        "The recovery flow felt calm, premium, and much more trustworthy than most travel products.",
      quoteAuthor: "David K. - Canada",
      shellTitle: "Forgot password",
      shellDescription:
        "Enter your email and we will send a one-time password to reset your account.",
      footerText: "Remember your password?",
      footerLink: "Back to login",
      infoEyebrow: "Secure recovery",
      infoBody:
        "We will send a six-digit code to your traveler email so only you can continue to a new password.",
      emailLabel: "Email address",
      emailPlaceholder: "alex@example.com",
      submitIdle: "Send reset OTP",
      submitLoading: "Sending OTP...",
      footerBadge: "Traveler security checkpoint",
    },
    verifyEmailPage: {
      badge: "Email security",
      title: "One small step before you begin.",
      description:
        "Verify your email with the OTP we just sent so your traveler account is protected from the start.",
      journeyLabel: "Activation gate",
      journeyTitle: "Traveler account verification",
      journeyDates: "Enter the 6-digit email code",
      stats: [
        { value: "6", label: "digits required" },
        { value: "OTP", label: "email challenge" },
        { value: "Now", label: "instant activation" },
      ],
      quote:
        "I loved that the sign-up flow stayed elegant all the way through verification.",
      quoteAuthor: "Mira S. - Germany",
      shellTitle: "Verify your email",
      shellDescription: "Enter the 6-digit OTP from your inbox to activate your account.",
      footerText: "Already verified?",
      footerLink: "Go to login",
      infoEyebrow: "Email protection",
      infoBody:
        "Use the code we just sent to confirm ownership of your traveler inbox before your first itinerary goes live.",
      emailLabel: "Email address",
      emailPlaceholder: "alex@example.com",
      otpLabel: "Verification OTP",
      submitIdle: "Verify account",
      submitLoading: "Verifying...",
      resendIdle: "Resend OTP",
      resendLoading: "Resending OTP...",
    },
    verifyResetPage: {
      badge: "OTP challenge",
      title: "Check your inbox for the reset code.",
      description:
        "Enter the one-time password we emailed you, then we will take you to the new password screen.",
      journeyLabel: "Recovery checkpoint",
      journeyTitle: "Reset-code confirmation",
      journeyDates: "Email OTP required",
      stats: [
        { value: "6", label: "digits to enter" },
        { value: "1", label: "next password step" },
        { value: "Fast", label: "recovery path" },
      ],
      quote:
        "The recovery flow felt polished enough that I never doubted where I was.",
      quoteAuthor: "Sophie T. - France",
      shellTitle: "Verify reset OTP",
      shellDescription: "Use the 6-digit OTP from your email to continue.",
      footerText: "Need a different email?",
      footerLink: "Start again",
      infoEyebrow: "Protected recovery",
      infoBody:
        "Confirm the reset code from your inbox and we will take you straight to the new-password screen.",
      emailLabel: "Email address",
      emailPlaceholder: "alex@example.com",
      otpLabel: "Reset OTP",
      submitIdle: "Continue",
      submitLoading: "Checking OTP...",
      resendIdle: "Resend OTP",
      resendLoading: "Resending OTP...",
    },
    resetPage: {
      badge: "Fresh credentials",
      title: "Create a password ready for the next trip.",
      description:
        "Your reset OTP is already confirmed. Set a new password and head back into your traveler dashboard.",
      journeyLabel: "Reset approved",
      journeyTitle: "Credential refresh complete",
      journeyDates: "New password required",
      stats: [
        { value: "2", label: "fields remaining" },
        { value: "OTP", label: "already confirmed" },
        { value: "Safe", label: "protected return" },
      ],
      quote:
        "Even the password reset step felt carefully designed instead of rushed together.",
      quoteAuthor: "Noah F. - United States",
      shellTitle: "Set new password",
      shellDescription: "Choose a new password for your account.",
      footerText: "Need a new OTP?",
      footerLink: "Request another one",
      infoEyebrow: "Password refresh",
      infoBody:
        "Choose a strong new password for the traveler account tied to this verified email.",
      emailLabel: "Email address",
      passwordLabel: "New password",
      passwordPlaceholder: "Create a new password",
      confirmPasswordLabel: "Confirm password",
      confirmPasswordPlaceholder: "Confirm your new password",
      passwordChecks: [
        "At least 8 characters",
        "Uppercase and lowercase letters",
        "One number or symbol",
      ],
      submitIdle: "Reset password",
      submitLoading: "Updating password...",
    },
  };
}
